discord:
  # The change applied when server restart
  token: "YOUR_BOT_TOKEN"
  prefix: "m"
  authorized_roles:
    - "123456789012345678"
    - "987654321098765432"

# Plugin settings
settings:
  # Language setting: en (English), vi (Vietnamese)
  locale: "vi"
