name: DiscordWhitelist
version: 1.0.1
main: dev.moonu.Whitelist.Main
api-version: 1.20
description: A plugin to manage Minecraft whitelist via Discord bot commands
author: MoonVN571

commands:
  discordwhitelist:
    description: Manage the DiscordWhitelist plugin
    aliases: [dw]
    usage: /<command> <reload|status>
    permission: discordwhitelist.use

permissions:
  discordwhitelist.admin:
    description: Admin permission for DiscordWhitelist
    default: op
    children:
      discordwhitelist.use: true
      discordwhitelist.admin.reload: true
      discordwhitelist.admin.status: true

  discordwhitelist.admin.reload:
    description: Allows reloading the DiscordWhitelist plugin
    default: op

  discordwhitelist.admin.status:
    description: Allows checking Discord bot status
    default: op