name: CI

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        
    - name: Cache Maven dependencies
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
        
    - name: Validate Maven project
      run: mvn validate
      
    - name: Compile project
      run: mvn clean compile
      
    - name: Run tests (if any)
      run: mvn test
      continue-on-error: true
      
    - name: Package plugin
      run: mvn package
      
    - name: Upload build artifacts (for debugging)
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: debug-artifacts
        path: |
          target/
          pom.xml
        retention-days: 7
